import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  
  allcontent: [
    // Documentation Parent
    {
      type: "category",
      label: "Documentation",
      className: "sidebar-all_docs",
      link: {
        type: "doc",
        id: "index",
      },
      collapsed: true,
      items: [
        // Platform Landing Page

        {
          type: "link",
          label: "Platform",
          className: "sidebar-platform",
          href: "/docs/platform",
          customProps: {
            description:
              "Learn how to manage Harness features that integrate with all modules.",
          },
        },
        // Continuous Integration landing page
        {
          type: "link",
          label: "Continuous Integration",
          className: "sidebar-ci",
          href: "/docs/continuous-integration",
          customProps: {
            description:
              "Learn how you can build faster and be more productive.",
          },
        },
        // Artifact Registry landing page
        {
          type: "link",
          label: "Artifact Registry ",
          className: "sidebar-ar",
          href: "/docs/artifact-registry",
          customProps: {
            description: "Store your artifacts natively with Harness."
          }
        },
        // Continuous Delivery Landing Page
        {
          type: "link",
          label: "Continuous Delivery & GitOps",
          className: "sidebar-cd",
          href: "/docs/continuous-delivery",
          customProps: {
            description:
              "Learn how to make your software releases more efficient and reliable.",
          },
        },
        // Infrastructure as Code Landing Page
        {
          type: "link",
          href: "/docs/infrastructure-as-code-management",
          label: "Infrastructure as Code Management",
          className: "sidebar-iacm",

          customProps: {
            description:
              "Get started with Harness Infrastructure as Code Management",
          },
        },
        // Cloud Cost Management Landing Page
        {
          type: "link",
          href: "/docs/cloud-cost-management",
          label: "Cloud Cost Management",
          className: "sidebar-ccm",

          customProps: {
            description: "Learn how to manage and optimize cloud costs.",
          },
        },
        {
          type: "category",
          label: "Harness Cloud Operations",
          link: {
            type: "generated-index",
            slug: "/harness-cloud-operations",
          },
          className: "sidebar-Cloud_Operations",
          customProps: {
            description: "Information on how the Harness SaaS is managed.",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "harness-cloud-operations",
            },
          ],
        },
        // Release Notes
        {
          type: "link",
          label: "Release Notes",
          className: "sidebar-Release_Notes",
          href: "/release-notes",
          customProps: {
            description: "Learn about recent changes to Harness products.",
          },
        }
      ],
    },
  ],
  //Additional Items in this parent can go here.
  //   individual module page sidebar start

  platform: [
    {
      type: "category",
      label: "Platform",
      className: "sidebar-platform",
      link: {
        type: "doc",
        id: "platform",
      },
      customProps: {
        description:
          "Learn how to manage Harness features that integrate with all modules.",
      },
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "platform",
        },
      ],
    },
    // Release Notes
    {
      type: "link",
      label: "Release Notes",
      className: "sidebar-Release_Notes",
      href: "/release-notes/platform",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
     // Roadmap
     {
      type: "link",
      label: "Roadmap",
      className: "sidebar-roadmap",
      href: "/roadmap/#platform",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
    // All Docs
    {
      type: "link",
      label: "Show All Docs",
      className: "sidebar-all_docs",
      href: "/docs",
      customProps: {
        description: "All Docs.",
      },
    },
  ],
  artifactregistry: [
    {
      type: "category",
      label: "Artifact Registry",
      className: "sidebar-ar",
      link: {
        type: "doc",
        id: "artifact-registry",
      },
      customProps: {
        description: "Learn how to store artifacts securely.",
      },
      collapsed: true,
      items: [
    {
      type: "html",
      value: "New to Artifact Registry?",
      className: "horizontal-bar",
    },
    "artifact-registry/get-started/overview", 
    "artifact-registry/get-started/quickstart",    
    {
      type: "html",
      value: "Use Artifact Registry",
      className: "horizontal-bar",
    },
    {
      type: "category",
      label: "Manage Registries",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "artifact-registry/manage-registries", } ],
    },
    {
      type: "category",
      label: "Manage Artifacts",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "artifact-registry/manage-artifacts", } ],
    },
    {
      type: "category",
      label: "Platform Integrations",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "artifact-registry/platform-integrations", } ],
    },
    {
      type: "html",
      value: "Troubleshooting & Resources",
      className: "horizontal-bar",
    },
    "artifact-registry/whats-supported",
    {
      type: "category",
      label: "Authorization & Authentication",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "artifact-registry/troubleshooting/authorization", } ],
    },
      ],
    },
    // API Docs
    {
      type: "link",
      label: "API Reference",
      className: "sidebar-API_Reference",
      href: "https://apidocs.harness.io/",
      customProps: {
        description: "Harness API Docs.",
      },
    },
    // All Docs
    {
      type: "link",
      label: "Show All Docs",
      className: "sidebar-all_docs",
      href: "/docs",
      customProps: {
        description: "All Docs.",
      },
    },
  ],
  continuousdelivery: [
    {
      type: "category",
      label: "Continuous Delivery & GitOps",
      className: "sidebar-cd",
      link: {
        type: "doc",
        id: "continuous-delivery",
      },
      customProps: {
        description:
          "Learn how to make your software releases more efficient and reliable.",
      },
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "continuous-delivery" }],
    }, // Release Notes
    {
      type: "link",
      label: "Release Notes",
      className: "sidebar-Release_Notes",
      href: "/release-notes/continuous-delivery",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
     // Roadmap
     {
      type: "link",
      label: "Roadmap",
      className: "sidebar-roadmap",
      href: "/roadmap/#cd",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
    // API Docs
    {
      type: "link",
      label: "API Reference",
      className: "sidebar-API_Reference",
      href: "https://apidocs.harness.io/",
      customProps: {
        description: "Harness API Docs.",
      },
    },
    // All Docs
    {
      type: "link",
      label: "Show All Docs",
      className: "sidebar-all_docs",
      href: "/docs",
      customProps: {
        description: "All Docs.",
      },
    },
  ], 
  infrastructureascodemanagement: [
    {
      type: "category",
      label: "Infrastructure as Code Management",
      className: "sidebar-iacm",
      link: {
        type: "doc",
        id: "infrastructure-as-code-management",
      },
      customProps: {
        description:
          "Get started with Harness Infrastructure as Code Management",
      },
      collapsed: true,
      items: [
    {
      type: "html",
      value: "New to IaCM?",
      className: "horizontal-bar",
    },
    "infra-as-code-management/get-started/overview",
    "infra-as-code-management/get-started/get-started",
    {
      type: "html",
      value: "Use IaCM",
      className: "horizontal-bar",
    },
    {
      type: "category",
      label: "Workspaces",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "infra-as-code-management/workspaces", } ],
    },
    {
      type: "category",
      label: "Pipelines",
      link: {
        type: "generated-index",
        slug:"/category/iacm-pipelines"
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "infra-as-code-management/pipelines", } ],
    },
    {
      type: "category",
      label: "Module Registry",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "infra-as-code-management/iacm-features/module-registry", } ],
    },
    {
      type: "category",
      label: "Policy & Governance",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "infra-as-code-management/policies-governance", } ],
    },
    {
      type: "category",
      label: "Project Settings",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "infra-as-code-management/project-setup", } ],
    },
    {
      type: "category",
      label: "Remote Backends",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "infra-as-code-management/remote-backends", } ],
    },
    {
      type: "category",
      label: "Reports & Insights",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [ { type: "autogenerated", dirName: "infra-as-code-management/reports-insights", } ],
    },
    {
      type: "html",
      value: "Troubleshooting & Resources",
      className: "horizontal-bar",
    },
    "infra-as-code-management/whats-supported",
    "infra-as-code-management/iacm-best-practices",
    "infra-as-code-management/iacm-security",
    "infra-as-code-management/faq",
    ]
  },
    // Release Notes
    {
      type: "link",
      label: "Release Notes",
      className: "sidebar-Release_Notes",
      href: "/release-notes/infrastructure-as-code-management",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
     // Roadmap
     {
      type: "link",
      label: "Roadmap",
      className: "sidebar-roadmap",
      href: "/roadmap/#iacm",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
    // API Docs
    {
      type: "link",
      label: "API Reference",
      className: "sidebar-API_Reference",
      href: "https://apidocs.harness.io/",
      customProps: {
        description: "Harness API Docs.",
      },
    },
    // All Docs
    {
      type: "link",
      label: "Show All Docs",
      className: "sidebar-all_docs",
      href: "/docs",
      customProps: {
        description: "All Docs.",
      },
    },
  ],
  
  cloudcostmanagement: [
    // Cloud Cost Management Landing Page
    {
      type: "category",
      label: "Cloud Cost Management",
      className: "sidebar-ccm",
      link: {
        type: "doc",
        id: "cloud-cost-management",
      },
      customProps: {
        description: "Learn how to manage and optimize cloud costs.",
      },
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "cloud-cost-management" }],
    }, // Release Notes
    {
      type: "link",
      label: "Release Notes",
      className: "sidebar-Release_Notes",
      href: "/release-notes/cloud-cost-management",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
     // Roadmap
     {
      type: "link",
      label: "Roadmap",
      className: "sidebar-roadmap",
      href: "/roadmap/#ccm",
      customProps: {
        description: "Learn about recent changes to Harness products.",
      },
    },
    // API Docs
    {
      type: "link",
      label: "API Reference",
      className: "sidebar-API_Reference",
      href: "https://apidocs.harness.io/",
      customProps: {
        description: "Harness API Docs.",
      },
    },
    // All Docs
    {
      type: "link",
      label: "Show All Docs",
      className: "sidebar-all_docs",
      href: "/docs",
      customProps: {
        description: "All Docs.",
      },
    },
  ],
};

export default sidebars;
